model:
  target: models.transformer.Transformer
  params:
    num_layers: 5
    mlp_layers: [0]
    dim_x: 5
    dim_y: 1
    dropout: 0.1
    nhead: 4
    proj_out: True
data:
  N: 10000
  C: 10
  Nx: 5
  Ny: 1
  Nf: 2
  epsW: 1.5 # this is kinda valid for this, will have to experiment for higher dimension
train:
  experiment: "complete"
  batch_sz: 32
  lr: 0.0005
  epochs: 100